use customer_support_behavior_analysis;
select * from customer_sb;

/* what is the total revenue generated by male vs female customers?*/ 
select gender, sum(purchase_amount)
from customer_sb
group by gender;

/* Which customers used a discount but still spent more than the average purchase amount */
select customer_id,purchase_amount
from customer_sb
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer_sb);

/* Which are the top 5 products with the highest average review rating*/
select item_purchased, round(avg(review_rating),2) as 'Average_Review_Rating'
from customer_sb
group by item_purchased
order by avg(review_rating) desc
limit 5;

/* Compare the average purchase amount between Standard and Express Shipping */
select shipping_type , round(avg(purchase_amount),2) as Average_purchase_amount
from customer_sb
where shipping_type in ('Express','Standard')
group by shipping_type;

/*Do Subscribed Customers spend more?*/
/*Compare Average spend and total revenue 
between subscribers and total between subscribers and non-subscribers */
select subscription_status, count(customer_id) as Total_Customers ,round(avg(purchase_amount),2) as Average_Spend, round(sum(purchase_amount),2) as total_revenue
from customer_sb
group by subscription_status
order by total_revenue, Average_Spend DESC;

/* Which 5 products have the highest percentage of purchases with disounts applied? */
select item_purchased,
(sum(case when discount_applied = 'Yes' then 1 else 0 end)) as Discounted_Purchases,
(sum(case when discount_applied = 'Yes' then 1 else 0 end) * 100 / count(*)) as Discount_Rate
from customer_sb
group by item_purchased
order by Discount_Rate Desc
limit 5;
/* Segment customers into New, Returning, and Loyal based on their total
number of previous purchases, and show the count of each segment */
with customer_type as(
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    End AS customer_segment
from customer_sb
)
select customer_segment, count(*) as "number of customers"
from customer_type
group by customer_segment;

/* What are the top 3 most purchased products within each category */
with item_counts as(
select category, item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) desc) as item_rank
FROM customer_sb
group by category, item_purchased 
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

/*Are Customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?*/
select subscription_status, count(customer_id) as repeat_buyers
from customer_sb
where previous_purchases > 5
group by subscription_status;

/*What is the revenue contribution of each age group*/
select age_group, sum(purchase_amount) as total_revenue
from customer_sb
group by age_group
order by total_revenue desc;






